[tox]
envlist = py39
minversion = 2.3
skipsdist = True
sitepackages=False

[stestr]
test_path=./tests

[testenv:py39]
basepython = python3.9
passenv = TOX_DEBUG_LEVEL
commands =
  stestr run {posargs}
  stestr slowest
deps =
  -r{toxinidir}/test-requirements.txt

[trixie]
basepython = python3.13
install_command = pip install \
    -c{env:UPPER_CONSTRAINTS_FILE:https://opendev.org/starlingx/root/raw/branch/master/build-tools/requirements/debian/trixie/upper-constraints.txt} \
    {opts} {packages}
deps =
  -r{toxinidir}/test-requirements-trixie.txt

[testenv:py313]
basepython = python3.13
passenv = TOX_DEBUG_LEVEL
install_command = {[trixie]install_command}
deps = {[trixie]deps}
commands =
  stestr run {posargs}
  stestr slowest
